<a href="https://colab.research.google.com/github/Natalya7oct/Feature-selection/blob/master/HW_MDS_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1:
Придумайте матрицы, которые обладают следующими свойствами:

a) диагональная, ортогональная, но не единичная(!):

b) верхнетреугольная, ортогональная:

c) нижнетреугольная, ортогональная:

d) матрица, у которой определитель = 1, и все элементы не равны 0:

e) матрица (3x3), у которой определитель = 1:

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

In [0]:
import numpy as np


In [8]:
m_a = np.array([[-1, 0],
              [0, -1]])
print(m_a)
# проверка
print(m_a.dot(m_a.T))

[[-1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]


In [15]:
m_b = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
print(m_b)
# проверка
print(m_b.dot(m_b.T))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
m_c = np.array([[-1, 0, 0],
              [0, -1, 0],
              [0, 0, -1]])
print(m_c)
# проверка
print(m_c.dot(m_c.T))

[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
m_d = np.array([[1, 1],
              [1, 2]])
print(m_d)
# проверка
print(np.linalg.det(m_d))

[[1 1]
 [1 2]]
1.0


In [16]:
m_e = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
print(m_e)
# проверка
print(np.linalg.det(m_e))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
1.0


Задание 2:
Найдите собственные значения и собственные вектора матриц (необходимо решение на numpy и честное решение на бумаге:)

In [21]:
m_2a = np.array([[2, 2],
              [1, 3]])
w, v = np.linalg.eig(m_2a)
print(w, v)

[1. 4.] [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [22]:
m_2b = np.array([[4, 1, -1],
              [1, 4, -1],
              [-1, -1, 4]])
w, v = np.linalg.eig(m_2b)
print(w, v)

[6. 3. 3.] [[-0.57735027 -0.81649658  0.15430335]
 [-0.57735027  0.40824829  0.6172134 ]
 [ 0.57735027 -0.40824829  0.77151675]]
